//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 232c040d-4a6c-4745-be35-3bdbbdf73911 aws-my-sample-app-android-v0.15";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:7b23ebb6-e9b7-4df3-9d17-f872f221fc89";
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_PnuV77TRB";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "1dq71ksd6qg6f35vol00pd8ee2";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1a6986jomv33o8emri3s1qqjq9kj2c4n193cdstn87bsh1m6e5i0";
}
